### ISSUE TITLE
Debian package is invalid

### ISSUE THREAD

**Issue by qwandor-google** [mdsteele/syzygy#1]
After following the instructions to build a Debian package (plus installing libsdl2-dev, without which the build failed), when I try to install it I get this error:

$ sudo dpkg -i /home/qwandor/src/syzygy/target/release/bundle/deb/syzygy_1.0.0_amd64.deb
dpkg: error processing archive /home/qwandor/src/syzygy/target/release/bundle/deb/syzygy_1.0.0_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
 invalid package name (character ' ' not allowed (only letters, digits and characters '-+._'))
Errors were encountered while processing:
 /home/qwandor/src/syzygy/target/release/bundle/deb/syzygy_1.0.0_amd64.deb

**Comment by mdsteele** [comment]
Whoops, sorry, I need to update those instructions.  As you have discovered, they are incomplete.

I believe the problem you're running into here is because you need to use the head version of cargo-bundle, rather than the current version published on crates.io (which is still missing some bugfixes).
